"""Import all ORM models so SQLAlchemy can resolve relationships."""

from .evaluation import (
    EvaluationDimension,
    EvaluationSubmission,
    EvaluationSubmissionItem,
    EvaluationTarget,
    EvaluationTask,
    EvaluationTemplate,
)
from .organization import (
    ClassStudent,
    Classroom,
    Course,
    Grade,
    School,
    StudentProfile,
    TeacherCourse,
    TeacherProfile,
    TimetableEntry,
    User,
)
from .scoring import (
    Exam,
    ExamClass,
    ExamCourse,
    ExamCourseScoreScheme,
    ScoreScheme,
    ScoreSchemeItem,
    StudentScoreItem,
    StudentScoreRecord,
)
from .workflow import (
    CertificateRequest,
    CertificateType,
    LeaveRequest,
    WorkflowActionLog,
    WorkflowInstance,
    WorkflowInstanceNode,
    WorkflowTask,
    WorkflowTemplate,
    WorkflowTemplateNode,
)

__all__ = [
    "CertificateRequest",
    "CertificateType",
    "Classroom",
    "ClassStudent",
    "Course",
    "EvaluationDimension",
    "EvaluationSubmission",
    "EvaluationSubmissionItem",
    "EvaluationTarget",
    "EvaluationTask",
    "EvaluationTemplate",
    "Exam",
    "ExamClass",
    "ExamCourse",
    "ExamCourseScoreScheme",
    "Grade",
    "LeaveRequest",
    "School",
    "ScoreScheme",
    "ScoreSchemeItem",
    "StudentProfile",
    "StudentScoreItem",
    "StudentScoreRecord",
    "TeacherCourse",
    "TeacherProfile",
    "TimetableEntry",
    "User",
    "WorkflowActionLog",
    "WorkflowInstance",
    "WorkflowInstanceNode",
    "WorkflowTask",
    "WorkflowTemplate",
    "WorkflowTemplateNode",
]
